dist: trusty
language: cpp
compiler: gcc

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5

install: 
  - sudo apt-get install lcov
  - pip install conan --user
  - conan user

script:    
  - g++ --version
  - mkdir -p build
  - cd build
  - conan install ..
  - cmake .. -DCMAKE_BUILD_TYPE=Coverage
  - make
  - make JWTUtilsTestCoverage
  - cd test
  - cd JWTUtilsTest
  - ctest

after_success:
  - bash <(curl -s https://codecov.io/bash)
